export { default as HomeLayout } from './HomeLayout'
export { default as Landing } from './Landing'
export { default as About } from './About'
export { default as Error } from './Error'
export { default as SingleMeal } from './SingleMeal'
export { default as Newsletter } from './Newsletter'
